// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210605120438_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68e14cb6-5266-48ff-870a-b5d2093f6e1d"),
                            Description = "Channel dedicated to Net Core",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            Id = new Guid("bd5bda26-da48-4698-b8b0-d0f520971eda"),
                            Description = "Channel dedicated to Angular",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("04cea954-d26f-4eb7-955d-eb29c1f332c1"),
                            Description = "Channel dedicated to React",
                            Name = "React"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
